# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Qnoiv-JifdvzfXbZjAjVH2_XLHPDQTN
"""

import numpy as np
a = np.zeros((3,4))
#questão 1 exercicio
b = np.random.randint(0,10,(3,4))
print(b)
#questão 2 exercicio
c = np.random.randint(0,10,(3,4))
print(c)
#questãão 3 exercicio
d = np.clip(c,1,4)
print(d)

#questão 4 exercicio
print(d.dtype)
print(d.shape)

#questão 5 exercicio
e = np.zeros((3,4))+2
e

#questão 6 exercicio
f = b+2*d

#questão 7 exercicio
g = np.array([2,3,4,5])
g

#questão 8 exercicio
h = np.multiply(b,g)
print(b)
print(f)

#questão 9 exercício
i = h
i

#questao 10 exercicio
b.sum()

#questao 11 exercicio
t = b
print(t)
t = t.astype(float)
print(t)
t.dtype

#questao 12 exercicio
x = b.T
x

#questao 13 exercicio
y = b.ravel()
y

#questao 14 exercicio
print(b)
y = np.random.randint(0,10,(1,4))
print(y)
w = np.append(b, y, axis=0)
print(w)

#questao 15 exercicio
z = np.array([0])
acrescimo = 1/4
for i in range(0,4):
  z = np.append(z, acrescimo)
  acrescimo = acrescimo + 0.2
print(z)
print(z.shape)